### ISSUE TITLE
Card stats bad layout

### ISSUE THREAD

**Issue by vbatecan** [Adrian-stuff/pshs-newsletter#8]
![image](https://github.com/Adrian-stuff/pshs-newsletter/assets/50913405/d7adb145-e33c-475c-bb4d-1b0fa23c450d)

**Comment by Adrian-stuff** [comment]
hindi need ng stats

**Comment by vbatecan** [comment]
Oh, I see.

**Comment by vbatecan** [comment]
I revert changes ko nalang
